/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bitcoin.gltf
Author: FranciscoDugarte (https://sketchfab.com/FranciscoDugarte)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-free-model-551901abb50a4166abdf5f7c92311d37
Title: BITCOIN - FREE MODEL
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bitcoin.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1096.736}>
        <mesh geometry={nodes['16783_Zeus_v1_NEW001_oro2_0'].geometry} material={materials.oro2} />
        <mesh geometry={nodes['16783_Zeus_v1_NEW001_oro2_0_1'].geometry} material={materials.oro2} />
        <mesh geometry={nodes['16783_Zeus_v1_NEW001_oro2_0_2'].geometry} material={materials.oro2} />
        <mesh geometry={nodes['16783_Zeus_v1_NEW001_oro2_0_3'].geometry} material={materials.oro2} />
      </group>
    </group>
  )
}

useGLTF.preload('/bitcoin.gltf')
